apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}/prometheus:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /prometheus
          name: prom-data
        - mountPath: /etc/prometheus
          name: prom-config
      volumes:
      - name: prom-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data
      - name: prom-config
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-config
