apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: default
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30006
