---
# Setup Prometheus with helm on Rocky Linux 9
# This playbook requires HELM to be installed
# TODO: set this up as a role or make this have dependencies on helm installation playbook
- name: Setup ansible playbook dependencies
  hosts: rocky,&prometheus
  become: true
  tasks:
  - name: make sure pip is installed
    dnf:
      name: python3-pip
      state: installed
  - name: install yaml dependencies
    ansible.builtin.pip:
      name: PyYAML
  - name: add directory for bind mount volumes
    file:
      path: "/home/ansible/prometheus/{{ item }}"
      owner: nobody
      group: nobody
      state: directory
    loop:
    - data
    - config
  - name: copy prometheus settings
    copy:
      src: prometheus-config/
      dest: /home/ansible/prometheus/config
      owner: nobody
      group: nobody
- name: Setup prometheus with helm
  hosts: rocky,&prometheus
  tasks:
  - name: remove stale chart files
    shell: rm -r /home/ansible/prometheus/chart/*
  - name: copy local chart to hosts
    copy:
      src: prometheus-chart/
      dest: /home/ansible/prometheus/chart/
  - name: install ansible helm repository
    kubernetes.core.helm:
      name: prometheus-1
      # helm module will look for the local chart directory on the managed machine, not from the controller
      chart_ref: "./prometheus/chart"
      release_namespace: default
