---
- name: Setup forgejo on Rocky Linux 9
  hosts: rocky,&forgejo
  vars:
    serviceName: forgejo
  tasks:
  - name: create nextcloud remote directory
    file:
      state: directory
      path: /home/ansible/{{ serviceName }}
  - name: upload compose file
    ansible.builtin.copy:
      src: compose.yml
      dest: /home/ansible/{{ serviceName }}/compose.yml
  - name: run docker compose
    community.docker.docker_compose_v2:
      project_src: /home/ansible/{{ serviceName }}
      state: present
- name: Change firewall
  hosts: rocky,&forgejo
  become: true
  tasks:
  - name: firewalld module dependencies
    dnf:
      name: python3-firewall
      state: installed
  - name: enable firewall ports
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    loop:
    - "3000/tcp"
    - "222/tcp"
