apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}/heimdall:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /config
          name: heimdall-config
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Pacific/Honolulu"
      volumes:
      - name: heimdall-config
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-config
